class Contact:
    case_id = "用例编号"
    case_module = "模块"
    case_description = "用例说明"
    request_address = "请求地址"
    request_method = "请求方式"
    request_param = "请求参数"
    request_header = "请求头"
    precondition = "前置条件"
    is_exec = "是否执行"
    status = "状态码"
    expect_result = "期望结果"
    actual_result = "实际结果"
    comment = "说明"
